
# CheckThat 2026 Task 3 — Stage 1 API Source Usability Triage

This notebook implements **Stage 0 + Stage 1** of the API-first pipeline:

- **Stage 0:** load the dataset split, flatten local scraped evidence JSON files, and create source-level records.
- **Stage 1:** call Vertex Gemini to decide whether each scraped source has usable readable text.

For this first run, the notebook limits the run to **10 claim IDs** and guarantees that these IDs are included:

```python
30349, 30350, 30352, 30353, 30357, 30358
```

Stage 1 does **not** judge claim relevance or truth. It only decides:

> Can this source be meaningfully inspected by later stages?

In [1]:

# Colab setup: install the Google GenAI SDK
!pip install -q -U google-genai pandas tqdm

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 52.6/52.6 kB 1.0 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 79.5/79.5 kB 2.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 791.9/791.9 kB 16.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.9/10.9 MB 47.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 245.6/245.6 kB 12.8 MB/s eta 0:00:00
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
google-colab 1.0.0 requires google-auth==2.47.0, but you have google-auth 2.52.0 which is incompatible.
google-colab 1.0.0 requires pandas==2.2.2, but you have pandas 3.0.2 which is incompatible.
google-cloud-aiplatform 1.148.1 requires google-genai<2.0.0,>=1.66.0; python_version >= "3.10", but you have google-genai 2.0.0 which is incompatible.
db-dtypes 1.5.1 requires pandas<3.0.0,>=1.5.3, but you have pandas 3.0.2 which is incompatible.
google-adk 1.29.0 requires google-genai<2.0.0,>=1.64.0, but you have google-genai 2.0.0 which is incompatible.
gradio 5.50.0 requires pandas<3.0,>=1.0, but you have pandas 3.0.2 which is incompatible.
bqplot 0.12.45 requires pandas<3.0.0,>=1.0.0, but you have pandas 3.0.2 which is incompatible.

In [2]:

# Authenticate to Google Cloud / Vertex AI
from google.colab import auth
auth.authenticate_user()

In [3]:

import os
import re
import json
import time
import tarfile
import zipfile
import random
import shutil
from pathlib import Path
from datetime import datetime, timezone
from concurrent.futures import ThreadPoolExecutor, as_completed

import pandas as pd
from tqdm.auto import tqdm

from google import genai
from google.genai import types


## 1. Configuration

Edit only this section if your dataset path or Google Cloud project differs.

Expected dataset layout after extraction:

```text
WatClaimCheck/
  train.json
  valid.json
  test.json
  articles/
```

In [4]:

# -----------------------------
# Google Cloud / Vertex settings
# -----------------------------
PROJECT_ID = "clef-checkthat"
LOCATION = "global"

os.environ["GOOGLE_CLOUD_PROJECT"] = PROJECT_ID
os.environ["GOOGLE_CLOUD_LOCATION"] = LOCATION
os.environ["GOOGLE_GENAI_USE_VERTEXAI"] = "True"

client = genai.Client(
    vertexai=True,
    project=PROJECT_ID,
    location=LOCATION,
)

# -----------------------------
# Stage 1 model settings
# -----------------------------
STAGE1_MODEL = "gemini-2.5-flash"
STAGE1_TEMPERATURE = 0.0
MAX_RETRIES = 5
MAX_WORKERS = 3
STAGE1_BATCH_SIZE = 4
SAVE_AFTER_EVERY_COMPLETED_BATCHES = 10

# -----------------------------
# Dataset / run settings
# -----------------------------
from google.colab import drive
drive.mount("/content/drive")

# Your dataset zip/tar file is in:
# My Drive / CheckThat_Task3_Dataset / WatClaimCheck.tar.gz
DATASET_ARCHIVE_PATH = Path("/content/drive/MyDrive/CheckThat_Task3_Dataset/test_dataset.zip")

# The notebook will extract it here inside Colab runtime
EXTRACT_ROOT = Path("/content/data")

# Keep this as None because we are extracting from the tar.gz file
DATA_ROOT_OVERRIDE = None

# Choose split. For the competition run, this will usually be "test".
SPLIT = "test"

REQUIRED_TARGET_IDS = []
N_TARGET_IDS = None
EXTRA_TARGET_IDS = []

# To control API cost, pass a packed source text to Stage 1.
# This is character-based, not token-based, but is simple and reliable for Colab.
MAX_SOURCE_CHARS_FOR_STAGE1 = 60_000
HEAD_CHARS = 45_000
TAIL_CHARS = 15_000

RUN_NAME = "test_dataset"
OUTPUT_ROOT = Path("/content/outputs")
STAGE0_OUT = OUTPUT_ROOT / "stage0" / f"flattened_sources_{RUN_NAME}.json"
STAGE1_OUT = OUTPUT_ROOT / "stage1" / f"stage1_api_triage_{RUN_NAME}.json"

OUTPUT_ROOT.mkdir(parents=True, exist_ok=True)
STAGE0_OUT.parent.mkdir(parents=True, exist_ok=True)
STAGE1_OUT.parent.mkdir(parents=True, exist_ok=True)

print("Configured Stage 1 run")
print("Project:", PROJECT_ID)
print("Location:", LOCATION)
print("Model:", STAGE1_MODEL)
print("Split:", SPLIT)
print("Required IDs:", REQUIRED_TARGET_IDS)
print("Output:", STAGE1_OUT)

Mounted at /content/drive
Configured Stage 1 run
Project: clef-checkthat
Location: global
Model: gemini-2.5-flash
Split: test
Required IDs: []
Output: /content/outputs/stage1/stage1_api_triage_test_dataset.json

In [5]:

# Optional smoke test: verify Vertex Gemini is reachable.
response = client.models.generate_content(
    model=STAGE1_MODEL,
    contents="Say only: Vertex Gemini test successful.",
    config=types.GenerateContentConfig(
        temperature=0.0,
        max_output_tokens=32,
    ),
)
print(response.text)

Vertex Gemini test successful.

In [6]:
from pathlib import Path
import shutil

DATASET_TAG = "test_dataset"
DRIVE_BASE = Path("/content/drive/MyDrive/CheckThat_Task3_Dataset")

paths_to_delete = [
    # Local Stage 0/1 outputs
    Path("/content/outputs/stage0") / f"flattened_sources_{DATASET_TAG}.json",
    Path("/content/outputs/stage1") / f"stage1_api_triage_{DATASET_TAG}.json",

    # Drive Stage 0/1 outputs
    DRIVE_BASE / "outputs/stage0" / f"flattened_sources_{DATASET_TAG}.json",
    DRIVE_BASE / "outputs/stage1" / f"stage1_api_triage_{DATASET_TAG}.json",

    # Optional downstream outputs for same dataset, so later stages also rerun cleanly
    DRIVE_BASE / "outputs/stage2" / f"stage2_extract_{DATASET_TAG}.json",
    DRIVE_BASE / "outputs/stage3" / f"stage3_packets_{DATASET_TAG}.json",
    DRIVE_BASE / "outputs/stage4" / f"stage4_articles_{DATASET_TAG}.json",
    DRIVE_BASE / "outputs/submission" / f"prediction_{DATASET_TAG}.json",
    DRIVE_BASE / "outputs/submission" / "prediction.json",
]

print("Deleting pipeline outputs for:", DATASET_TAG)
print()

for p in paths_to_delete:
    if p.exists():
        p.unlink()
        print("Deleted:", p)
    else:
        print("Not found:", p)

print("\nDone. Now run the notebook from the top.")

Deleting pipeline outputs for: test_dataset

Not found: /content/outputs/stage0/flattened_sources_test_dataset.json
Not found: /content/outputs/stage1/stage1_api_triage_test_dataset.json
Not found: /content/drive/MyDrive/CheckThat_Task3_Dataset/outputs/stage0/flattened_sources_test_dataset.json
Not found: /content/drive/MyDrive/CheckThat_Task3_Dataset/outputs/stage1/stage1_api_triage_test_dataset.json
Not found: /content/drive/MyDrive/CheckThat_Task3_Dataset/outputs/stage2/stage2_extract_test_dataset.json
Not found: /content/drive/MyDrive/CheckThat_Task3_Dataset/outputs/stage3/stage3_packets_test_dataset.json
Not found: /content/drive/MyDrive/CheckThat_Task3_Dataset/outputs/stage4/stage4_articles_test_dataset.json
Not found: /content/drive/MyDrive/CheckThat_Task3_Dataset/outputs/submission/prediction_test_dataset.json
Deleted: /content/drive/MyDrive/CheckThat_Task3_Dataset/outputs/submission/prediction.json

Done. Now run the notebook from the top.


## 2. Locate and load the dataset

This cell extracts `WatClaimCheck.tar.gz` if needed, then finds the directory that contains the split files and `articles/`.

In [7]:

def find_data_root(search_root: Path) -> Path:
    """Find a directory containing split JSON files and an evidence/articles folder."""
    candidates = []

    for p in [search_root] + list(search_root.rglob("*")):
        if not p.is_dir():
            continue

        has_any_split = any((p / f"{name}.json").exists() for name in ["train", "valid", "test"])
        has_evidence_folder = any((p / name).exists() for name in ["articles", "evidence_docs", "evidence"])

        if has_any_split and has_evidence_folder:
            candidates.append(p)

    if not candidates:
        raise FileNotFoundError(
            f"Could not find dataset root under {search_root}. "
            f"Expected train/valid/test JSON and articles/ or evidence_docs/."
        )

    return sorted(candidates, key=lambda x: len(x.parts))[0]

def maybe_extract_dataset() -> Path:
    if DATA_ROOT_OVERRIDE is not None:
        root = Path(DATA_ROOT_OVERRIDE)
        if not root.exists():
            raise FileNotFoundError(f"DATA_ROOT_OVERRIDE does not exist: {root}")
        return root

    if DATASET_ARCHIVE_PATH.exists():
        EXTRACT_ROOT.mkdir(parents=True, exist_ok=True)

        marker_name = ".test_dataset_extracted"
        marker = EXTRACT_ROOT / marker_name

        if not marker.exists():
            print(f"Extracting {DATASET_ARCHIVE_PATH} to {EXTRACT_ROOT} ...")

            suffixes = "".join(DATASET_ARCHIVE_PATH.suffixes).lower()

            if suffixes.endswith(".zip"):
                with zipfile.ZipFile(DATASET_ARCHIVE_PATH, "r") as z:
                    z.extractall(EXTRACT_ROOT)
            elif suffixes.endswith(".tar.gz") or suffixes.endswith(".tgz"):
                with tarfile.open(DATASET_ARCHIVE_PATH, "r:gz") as tar:
                    tar.extractall(EXTRACT_ROOT)
            else:
                raise ValueError(f"Unsupported archive format: {DATASET_ARCHIVE_PATH}")

            marker.write_text(datetime.now(timezone.utc).isoformat())

        return find_data_root(EXTRACT_ROOT)

    for root in [Path("/content/test_dataset"), Path("/content/data/test_dataset"), Path("/content/data")]:
        if root.exists():
            try:
                return find_data_root(root)
            except FileNotFoundError:
                pass

    raise FileNotFoundError(
        f"Dataset not found. Expected archive at {DATASET_ARCHIVE_PATH}, or set DATA_ROOT_OVERRIDE."
    )


def load_json(path: Path):
    with path.open("r", encoding="utf-8") as f:
        return json.load(f)

DATA_ROOT = maybe_extract_dataset()

if (DATA_ROOT / "articles").exists():
    ARTICLES_DIR = DATA_ROOT / "articles"
elif (DATA_ROOT / "evidence_docs").exists():
    ARTICLES_DIR = DATA_ROOT / "evidence_docs"
elif (DATA_ROOT / "evidence").exists():
    ARTICLES_DIR = DATA_ROOT / "evidence"
else:
    raise FileNotFoundError(
        f"Could not find evidence folder under {DATA_ROOT}. "
        "Expected articles/, evidence_docs/, or evidence/."
    )

SPLIT_PATH = DATA_ROOT / f"{SPLIT}.json"

if not SPLIT_PATH.exists():
    available = [p.name for p in DATA_ROOT.glob("*.json")]
    raise FileNotFoundError(f"Split file not found: {SPLIT_PATH}. Available JSON files: {available}")

examples = load_json(SPLIT_PATH)
print("DATA_ROOT:", DATA_ROOT)
print("ARTICLES_DIR:", ARTICLES_DIR)
print("SPLIT_PATH:", SPLIT_PATH)
print("Number of examples in split:", len(examples))

Extracting /content/drive/MyDrive/CheckThat_Task3_Dataset/test_dataset.zip to /content/data ...
DATA_ROOT: /content/data/test_dataset
ARTICLES_DIR: /content/data/test_dataset/evidence_docs
SPLIT_PATH: /content/data/test_dataset/test.json
Number of examples in split: 1158


## 3. Select exactly 10 target IDs

The six required IDs are checked first. The remaining slots are auto-filled from the chosen split unless `EXTRA_TARGET_IDS` is provided.

In [8]:

def get_claim_id(example) -> str:
    """Robustly read the claim id across possible dataset variants."""
    for candidate in [
        example.get("target_id"),
        example.get("id"),
        example.get("metadata", {}).get("id"),
        example.get("label", {}).get("target_id"),
    ]:
        if candidate is not None:
            return str(candidate)
    raise KeyError(f"Could not find claim id in example keys: {list(example.keys())}")


# Full dataset run: process every claim in the selected split.
TARGET_IDS = [get_claim_id(ex) for ex in examples]

print("Full dataset mode.")
print("Number of TARGET_IDS:", len(TARGET_IDS))
print("First 10 TARGET_IDS:", TARGET_IDS[:10])

Full dataset mode.
Number of TARGET_IDS: 1158
First 10 TARGET_IDS: ['30354_exclaim', '30355_exclaim', '30356_exclaim', '30360_exclaim', '30361_exclaim', '30364_exclaim', '30365_exclaim', '30366_exclaim', '30367_exclaim', '30369_exclaim']


## 4. Stage 0 — flatten local evidence JSON files

Important leakage rule: this notebook uses only `metadata.premise_articles`. It does **not** load `label.review_article` as normal evidence.

In [9]:
def get_claim_text(example) -> str:
    return (
        example.get("metadata", {}).get("claim")
        or example.get("claim")
        or example.get("text")
        or ""
    )


def get_original_rating(example):
    label = example.get("label", {}) or {}
    return label.get("original_rating", label.get("rating", ""))


def get_premise_articles(example) -> dict:
    metadata = example.get("metadata", {}) or {}
    premise = metadata.get("premise_articles") or example.get("premise_articles") or {}
    if not isinstance(premise, dict):
        raise TypeError(f"Expected premise_articles to be a dict, got {type(premise)}")
    return premise


def flatten_article_json(article_json) -> str:
    """Flatten scraped JSON content into readable text for the API."""
    if article_json is None:
        return ""
    if isinstance(article_json, list):
        parts = []
        for x in article_json:
            if x is None:
                continue
            if isinstance(x, (dict, list)):
                parts.append(json.dumps(x, ensure_ascii=False, indent=2))
            else:
                s = str(x).strip()
                if s:
                    parts.append(s)
        return "\n".join(parts)
    if isinstance(article_json, dict):
        return json.dumps(article_json, ensure_ascii=False, indent=2)
    return str(article_json)


def pack_source_text(text: str, max_chars=MAX_SOURCE_CHARS_FOR_STAGE1) -> str:
    """Keep the beginning and end of very long sources to control API cost."""
    text = text or ""
    if len(text) <= max_chars:
        return text
    head = text[:HEAD_CHARS]
    tail = text[-TAIL_CHARS:]
    omitted = len(text) - len(head) - len(tail)
    return (
        head
        + f"\n\n[... omitted {omitted} characters from the middle of this scraped source ...]\n\n"
        + tail
    )


def safe_read_article_json(article_path: Path):
    try:
        with article_path.open("r", encoding="utf-8") as f:
            return json.load(f), None
    except Exception as e:
        return None, repr(e)


def iter_file_names(value):
    """premise_articles normally maps URL -> file_name, but handle list variants just in case."""
    if isinstance(value, list):
        for x in value:
            yield str(x)
    elif value is None:
        return
    else:
        yield str(value)


def build_source_records(examples, target_ids):
    target_set = set(str(x) for x in target_ids)
    records = []

    for ex in examples:
        cid = get_claim_id(ex)
        if cid not in target_set:
            continue

        claim = get_claim_text(ex)
        original_rating = get_original_rating(ex)
        premise_articles = get_premise_articles(ex)

        for url, file_value in premise_articles.items():
            for file_name in iter_file_names(file_value):
                article_path = ARTICLES_DIR / file_name
                article_json, load_error = safe_read_article_json(article_path)
                full_text = flatten_article_json(article_json) if load_error is None else ""
                packed_text = pack_source_text(full_text)

                records.append({
                    "id": cid,
                    "claim": claim,
                    "original_rating": original_rating,
                    "url": str(url),
                    "file_name": file_name,
                    "article_path": str(article_path),
                    "source_text": packed_text,
                    "source_text_original_chars": len(full_text or ""),
                    "source_text_packed_chars": len(packed_text or ""),
                    "source_text_was_packed": len(full_text or "") > len(packed_text or ""),
                    "load_error": load_error,
                    "stage": "stage0_flattened_source",
                })

    return records

source_records = build_source_records(examples, TARGET_IDS)

print("Number of source-level records:", len(source_records))
print("Claims represented:", sorted({r["id"] for r in source_records}))

# Save Stage 0 output for debugging and resume support.
with STAGE0_OUT.open("w", encoding="utf-8") as f:
    json.dump(source_records, f, ensure_ascii=False, indent=2)

print("Saved Stage 0 flattened sources to:", STAGE0_OUT)

pd.DataFrame(source_records)[[
    "id", "file_name", "url", "source_text_original_chars", "source_text_packed_chars", "load_error"
]].head(20)

Number of source-level records: 8979
Claims represented: ['0_ambigsnopes', '100_ambigsnopes', '104_ambigsnopes', '106_ambigsnopes', '107_ambigsnopes', '109_ambigsnopes', '111_ambigsnopes', '113_ambigsnopes', '114_ambigsnopes', '116_ambigsnopes', '117_ambigsnopes', '118_ambigsnopes', '11_ambigsnopes', '120_ambigsnopes', '122_ambigsnopes', '124_ambigsnopes', '125_ambigsnopes', '127_ambigsnopes', '128_ambigsnopes', '129_ambigsnopes', '12_ambigsnopes', '130_ambigsnopes', '131_ambigsnopes', '133_ambigsnopes', '134_ambigsnopes', '135_ambigsnopes', '136_ambigsnopes', '139_ambigsnopes', '13_ambigsnopes', '140_ambigsnopes', '142_ambigsnopes', '144_ambigsnopes', '145_ambigsnopes', '146_ambigsnopes', '147_ambigsnopes', '148_ambigsnopes', '149_ambigsnopes', '14_ambigsnopes', '150_ambigsnopes', '151_ambigsnopes', '153_ambigsnopes', '154_ambigsnopes', '157_ambigsnopes', '158_ambigsnopes', '159_ambigsnopes', '161_ambigsnopes', '162_ambigsnopes', '163_ambigsnopes', '164_ambigsnopes', '165_ambigsnopes', '166_ambigsnopes', '167_ambigsnopes', '168_ambigsnopes', '169_ambigsnopes', '16_ambigsnopes', '170_ambigsnopes', '171_ambigsnopes', '172_ambigsnopes', '173_ambigsnopes', '175_ambigsnopes', '176_ambigsnopes', '177_ambigsnopes', '178_ambigsnopes', '179_ambigsnopes', '180_ambigsnopes', '181_ambigsnopes', '182_ambigsnopes', '184_ambigsnopes', '185_ambigsnopes', '186_ambigsnopes', '187_ambigsnopes', '188_ambigsnopes', '189_ambigsnopes', '190_ambigsnopes', '191_ambigsnopes', '192_ambigsnopes', '193_ambigsnopes', '194_ambigsnopes', '196_ambigsnopes', '197_ambigsnopes', '198_ambigsnopes', '199_ambigsnopes', '19_ambigsnopes', '1_ambigsnopes', '200_ambigsnopes', '201_ambigsnopes', '204_ambigsnopes', '205_ambigsnopes', '206_ambigsnopes', '207_ambigsnopes', '208_ambigsnopes', '209_ambigsnopes', '210_ambigsnopes', '211_ambigsnopes', '212_ambigsnopes', '213_ambigsnopes', '214_ambigsnopes', '215_ambigsnopes', '216_ambigsnopes', '217_ambigsnopes', '218_ambigsnopes', '25_ambigsnopes', '26_ambigsnopes', '27_ambigsnopes', '28_ambigsnopes', '29_ambigsnopes', '2_ambigsnopes', '30354_exclaim', '30355_exclaim', '30356_exclaim', '30360_exclaim', '30361_exclaim', '30364_exclaim', '30365_exclaim', '30366_exclaim', '30367_exclaim', '30369_exclaim', '30373_exclaim', '30385_exclaim', '30389_exclaim', '30391_exclaim', '30410_exclaim', '30414_exclaim', '30420_exclaim', '30425_exclaim', '30439_exclaim', '30440_exclaim', '30442_exclaim', '30445_exclaim', '30450_exclaim', '30452_exclaim', '30454_exclaim', '30457_exclaim', '30464_exclaim', '30471_exclaim', '30476_exclaim', '30480_exclaim', '30482_exclaim', '30485_exclaim', '30489_exclaim', '30490_exclaim', '30493_exclaim', '30497_exclaim', '30498_exclaim', '30499_exclaim', '30507_exclaim', '30511_exclaim', '30512_exclaim', '30514_exclaim', '30515_exclaim', '30519_exclaim', '30521_exclaim', '30522_exclaim', '30523_exclaim', '30527_exclaim', '30539_exclaim', '30541_exclaim', '30551_exclaim', '30555_exclaim', '30560_exclaim', '30561_exclaim', '30569_exclaim', '30570_exclaim', '30573_exclaim', '30577_exclaim', '30578_exclaim', '30585_exclaim', '30589_exclaim', '30590_exclaim', '30591_exclaim', '30592_exclaim', '30596_exclaim', '30603_exclaim', '30608_exclaim', '30615_exclaim', '30616_exclaim', '30618_exclaim', '30622_exclaim', '30630_exclaim', '30632_exclaim', '30640_exclaim', '30644_exclaim', '30649_exclaim', '30651_exclaim', '30656_exclaim', '30660_exclaim', '30661_exclaim', '30665_exclaim', '30666_exclaim', '30669_exclaim', '30670_exclaim', '30675_exclaim', '30677_exclaim', '30679_exclaim', '30693_exclaim', '30694_exclaim', '30695_exclaim', '30696_exclaim', '30697_exclaim', '30700_exclaim', '30706_exclaim', '30707_exclaim', '30712_exclaim', '30713_exclaim', '30714_exclaim', '30717_exclaim', '30718_exclaim', '30720_exclaim', '30724_exclaim', '30726_exclaim', '30733_exclaim', '30745_exclaim', '30749_exclaim', '30755_exclaim', '30758_exclaim', '30759_exclaim', '30761_exclaim', '30763_exclaim', '30772_exclaim', '30774_exclaim', '30776_exclaim', '30783_exclaim', '30785_exclaim', '30786_exclaim', '30788_exclaim', '30791_exclaim', '30793_exclaim', '30794_exclaim', '30795_exclaim', '30800_exclaim', '30809_exclaim', '30810_exclaim', '30811_exclaim', '30813_exclaim', '30815_exclaim', '30818_exclaim', '30822_exclaim', '30823_exclaim', '30825_exclaim', '30829_exclaim', '30832_exclaim', '30837_exclaim', '30840_exclaim', '30841_exclaim', '30843_exclaim', '30850_exclaim', '30853_exclaim', '30857_exclaim', '30859_exclaim', '30862_exclaim', '30867_exclaim', '30874_exclaim', '30876_exclaim', '30880_exclaim', '30881_exclaim', '30891_exclaim', '30895_exclaim', '30897_exclaim', '30899_exclaim', '30902_exclaim', '30903_exclaim', '30906_exclaim', '30908_exclaim', '30912_exclaim', '30913_exclaim', '30917_exclaim', '30923_exclaim', '30927_exclaim', '30934_exclaim', '30935_exclaim', '30936_exclaim', '30938_exclaim', '30940_exclaim', '30944_exclaim', '30948_exclaim', '30955_exclaim', '30961_exclaim', '30962_exclaim', '30965_exclaim', '30972_exclaim', '30975_exclaim', '30981_exclaim', '30982_exclaim', '30986_exclaim', '30991_exclaim', '30_ambigsnopes', '31001_exclaim', '31002_exclaim', '31003_exclaim', '31008_exclaim', '31010_exclaim', '31011_exclaim', '31015_exclaim', '31017_exclaim', '31027_exclaim', '31031_exclaim', '31034_exclaim', '31037_exclaim', '31039_exclaim', '31041_exclaim', '31043_exclaim', '31045_exclaim', '31047_exclaim', '31048_exclaim', '31052_exclaim', '31053_exclaim', '31058_exclaim', '31061_exclaim', '31072_exclaim', '31073_exclaim', '31077_exclaim', '31085_exclaim', '31086_exclaim', '31089_exclaim', '31092_exclaim', '31094_exclaim', '31097_exclaim', '31108_exclaim', '31109_exclaim', '31110_exclaim', '31111_exclaim', '31113_exclaim', '31116_exclaim', '31118_exclaim', '31125_exclaim', '31130_exclaim', '31132_exclaim', '31133_exclaim', '31134_exclaim', '31135_exclaim', '31137_exclaim', '31141_exclaim', '31142_exclaim', '31143_exclaim', '31144_exclaim', '31146_exclaim', '31150_exclaim', '31151_exclaim', '31153_exclaim', '31156_exclaim', '31157_exclaim', '31162_exclaim', '31167_exclaim', '31172_exclaim', '31173_exclaim', '31177_exclaim', '31180_exclaim', '31181_exclaim', '31183_exclaim', '31184_exclaim', '31186_exclaim', '31191_exclaim', '31193_exclaim', '31195_exclaim', '31202_exclaim', '31203_exclaim', '31206_exclaim', '31208_exclaim', '31212_exclaim', '31214_exclaim', '31220_exclaim', '31228_exclaim', '31239_exclaim', '31250_exclaim', '31252_exclaim', '31253_exclaim', '31263_exclaim', '31266_exclaim', '31272_exclaim', '31276_exclaim', '31277_exclaim', '31278_exclaim', '31281_exclaim', '31283_exclaim', '31284_exclaim', '31285_exclaim', '31287_exclaim', '31293_exclaim', '31297_exclaim', '31298_exclaim', '31299_exclaim', '31302_exclaim', '31306_exclaim', '31318_exclaim', '31324_exclaim', '31329_exclaim', '31334_exclaim', '31335_exclaim', '31338_exclaim', '31339_exclaim', '31346_exclaim', '31349_exclaim', '31352_exclaim', '31354_exclaim', '31357_exclaim', '31359_exclaim', '31363_exclaim', '31366_exclaim', '31368_exclaim', '31370_exclaim', '31371_exclaim', '31373_exclaim', '31374_exclaim', '31378_exclaim', '31381_exclaim', '31383_exclaim', '31386_exclaim', '31387_exclaim', '31388_exclaim', '31389_exclaim', '31390_exclaim', '31391_exclaim', '31394_exclaim', '31396_exclaim', '31401_exclaim', '31409_exclaim', '31415_exclaim', '31418_exclaim', '31421_exclaim', '31425_exclaim', '31429_exclaim', '31430_exclaim', '31434_exclaim', '31435_exclaim', '31436_exclaim', '31438_exclaim', '31441_exclaim', '31444_exclaim', '31450_exclaim', '31453_exclaim', '31461_exclaim', '31466_exclaim', '31468_exclaim', '31472_exclaim', '31474_exclaim', '31477_exclaim', '31478_exclaim', '31481_exclaim', '31482_exclaim', '31483_exclaim', '31486_exclaim', '31487_exclaim', '31489_exclaim', '31490_exclaim', '31491_exclaim', '31493_exclaim', '31504_exclaim', '31505_exclaim', '31512_exclaim', '31514_exclaim', '31521_exclaim', '31527_exclaim', '31531_exclaim', '31536_exclaim', '31543_exclaim', '31546_exclaim', '31548_exclaim', '31555_exclaim', '31558_exclaim', '31563_exclaim', '31569_exclaim', '31576_exclaim', '31577_exclaim', '31592_exclaim', '31593_exclaim', '31595_exclaim', '31598_exclaim', '31599_exclaim', '31602_exclaim', '31603_exclaim', '31605_exclaim', '31607_exclaim', '31611_exclaim', '31613_exclaim', '31614_exclaim', '31621_exclaim', '31626_exclaim', '31628_exclaim', '31630_exclaim', '31634_exclaim', '31636_exclaim', '31637_exclaim', '31641_exclaim', '31648_exclaim', '31658_exclaim', '31659_exclaim', '31662_exclaim', '31672_exclaim', '31676_exclaim', '31677_exclaim', '31678_exclaim', '31679_exclaim', '31682_exclaim', '31687_exclaim', '31694_exclaim', '31702_exclaim', '31703_exclaim', '31706_exclaim', '31708_exclaim', '31717_exclaim', '31718_exclaim', '31719_exclaim', '31721_exclaim', '31724_exclaim', '31726_exclaim', '31728_exclaim', '31729_exclaim', '31730_exclaim', '31731_exclaim', '31732_exclaim', '31733_exclaim', '31743_exclaim', '31744_exclaim', '31745_exclaim', '31747_exclaim', '31751_exclaim', '31752_exclaim', '31753_exclaim', '31761_exclaim', '31765_exclaim', '31766_exclaim', '31767_exclaim', '31769_exclaim', '31770_exclaim', '31777_exclaim', '31779_exclaim', '31785_exclaim', '31789_exclaim', '31798_exclaim', '31803_exclaim', '31807_exclaim', '31808_exclaim', '31811_exclaim', '31813_exclaim', '31828_exclaim', '31831_exclaim', '31833_exclaim', '31837_exclaim', '31845_exclaim', '31849_exclaim', '31854_exclaim', '31855_exclaim', '31864_exclaim', '31870_exclaim', '31871_exclaim', '31875_exclaim', '31877_exclaim', '31882_exclaim', '31892_exclaim', '31894_exclaim', '31895_exclaim', '31898_exclaim', '31900_exclaim', '31902_exclaim', '31909_exclaim', '31916_exclaim', '31919_exclaim', '31920_exclaim', '31922_exclaim', '31923_exclaim', '31932_exclaim', '31934_exclaim', '31936_exclaim', '31939_exclaim', '31942_exclaim', '31946_exclaim', '31947_exclaim', '31955_exclaim', '31956_exclaim', '31966_exclaim', '31967_exclaim', '31976_exclaim', '31977_exclaim', '31988_exclaim', '31989_exclaim', '31990_exclaim', '31992_exclaim', '31995_exclaim', '31996_exclaim', '31998_exclaim', '31_ambigsnopes', '32001_exclaim', '32010_exclaim', '32012_exclaim', '32021_exclaim', '32025_exclaim', '32026_exclaim', '32028_exclaim', '32031_exclaim', '32035_exclaim', '32040_exclaim', '32042_exclaim', '32049_exclaim', '32051_exclaim', '32054_exclaim', '32055_exclaim', '32057_exclaim', '32058_exclaim', '32060_exclaim', '32062_exclaim', '32067_exclaim', '32069_exclaim', '32071_exclaim', '32072_exclaim', '32073_exclaim', '32075_exclaim', '32080_exclaim', '32083_exclaim', '32086_exclaim', '32093_exclaim', '32097_exclaim', '32098_exclaim', '32101_exclaim', '32110_exclaim', '32113_exclaim', '32116_exclaim', '32128_exclaim', '32130_exclaim', '32131_exclaim', '32136_exclaim', '32138_exclaim', '32142_exclaim', '32149_exclaim', '32150_exclaim', '32153_exclaim', '32155_exclaim', '32157_exclaim', '32161_exclaim', '32165_exclaim', '32166_exclaim', '32169_exclaim', '32182_exclaim', '32190_exclaim', '32192_exclaim', '32196_exclaim', '32197_exclaim', '32200_exclaim', '32201_exclaim', '32207_exclaim', '32209_exclaim', '32210_exclaim', '32217_exclaim', '32220_exclaim', '32224_exclaim', '32225_exclaim', '32230_exclaim', '32234_exclaim', '32241_exclaim', '32245_exclaim', '32250_exclaim', '32252_exclaim', '32253_exclaim', '32256_exclaim', '32258_exclaim', '32260_exclaim', '32263_exclaim', '32270_exclaim', '32283_exclaim', '32286_exclaim', '32291_exclaim', '32292_exclaim', '32293_exclaim', '32294_exclaim', '32297_exclaim', '32301_exclaim', '32304_exclaim', '32305_exclaim', '32307_exclaim', '32316_exclaim', '32319_exclaim', '32320_exclaim', '32323_exclaim', '32326_exclaim', '32327_exclaim', '32331_exclaim', '32335_exclaim', '32336_exclaim', '32340_exclaim', '32343_exclaim', '32345_exclaim', '32347_exclaim', '32352_exclaim', '32359_exclaim', '32361_exclaim', '32365_exclaim', '32367_exclaim', '32368_exclaim', '32371_exclaim', '32372_exclaim', '32373_exclaim', '32374_exclaim', '32377_exclaim', '32378_exclaim', '32380_exclaim', '32385_exclaim', '32391_exclaim', '32396_exclaim', '32400_exclaim', '32401_exclaim', '32403_exclaim', '32405_exclaim', '32408_exclaim', '32416_exclaim', '32419_exclaim', '32426_exclaim', '32428_exclaim', '32430_exclaim', '32435_exclaim', '32445_exclaim', '32446_exclaim', '32449_exclaim', '32450_exclaim', '32453_exclaim', '32458_exclaim', '32460_exclaim', '32461_exclaim', '32462_exclaim', '32465_exclaim', '32467_exclaim', '32468_exclaim', '32470_exclaim', '32479_exclaim', '32482_exclaim', '32487_exclaim', '32490_exclaim', '32491_exclaim', '32495_exclaim', '32497_exclaim', '32498_exclaim', '32500_exclaim', '32502_exclaim', '32503_exclaim', '32504_exclaim', '32505_exclaim', '32510_exclaim', '32519_exclaim', '32522_exclaim', '32523_exclaim', '32532_exclaim', '32536_exclaim', '32538_exclaim', '32539_exclaim', '32542_exclaim', '32545_exclaim', '32549_exclaim', '32552_exclaim', '32556_exclaim', '32562_exclaim', '32566_exclaim', '32572_exclaim', '32576_exclaim', '32579_exclaim', '32580_exclaim', '32581_exclaim', '32584_exclaim', '32585_exclaim', '32587_exclaim', '32597_exclaim', '32598_exclaim', '32602_exclaim', '32611_exclaim', '32612_exclaim', '32615_exclaim', '32618_exclaim', '32625_exclaim', '32634_exclaim', '32637_exclaim', '32639_exclaim', '32643_exclaim', '32645_exclaim', '32651_exclaim', '32653_exclaim', '32656_exclaim', '32663_exclaim', '32664_exclaim', '32678_exclaim', '32682_exclaim', '32686_exclaim', '32689_exclaim', '32691_exclaim', '32693_exclaim', '32696_exclaim', '32699_exclaim', '32701_exclaim', '32702_exclaim', '32705_exclaim', '32707_exclaim', '32711_exclaim', '32716_exclaim', '32721_exclaim', '32722_exclaim', '32728_exclaim', '32731_exclaim', '32733_exclaim', '32734_exclaim', '32736_exclaim', '32738_exclaim', '32740_exclaim', '32742_exclaim', '32745_exclaim', '32750_exclaim', '32758_exclaim', '32764_exclaim', '32766_exclaim', '32779_exclaim', '32781_exclaim', '32782_exclaim', '32785_exclaim', '32786_exclaim', '32788_exclaim', '32793_exclaim', '32794_exclaim', '32796_exclaim', '32800_exclaim', '32801_exclaim', '32803_exclaim', '32814_exclaim', '32817_exclaim', '32818_exclaim', '32819_exclaim', '32820_exclaim', '32825_exclaim', '32827_exclaim', '32828_exclaim', '32829_exclaim', '32832_exclaim', '32833_exclaim', '32837_exclaim', '32846_exclaim', '32847_exclaim', '32849_exclaim', '32852_exclaim', '32860_exclaim', '32861_exclaim', '32862_exclaim', '32864_exclaim', '32865_exclaim', '32866_exclaim', '32867_exclaim', '32871_exclaim', '32875_exclaim', '32876_exclaim', '32880_exclaim', '32881_exclaim', '32888_exclaim', '32890_exclaim', '32891_exclaim', '32892_exclaim', '32895_exclaim', '32897_exclaim', '32898_exclaim', '32902_exclaim', '32906_exclaim', '32908_exclaim', '32910_exclaim', '32912_exclaim', '32917_exclaim', '32918_exclaim', '32920_exclaim', '32923_exclaim', '32930_exclaim', '32939_exclaim', '32944_exclaim', '32946_exclaim', '32950_exclaim', '32951_exclaim', '32953_exclaim', '32956_exclaim', '32957_exclaim', '32958_exclaim', '32962_exclaim', '32967_exclaim', '32972_exclaim', '32975_exclaim', '32976_exclaim', '32977_exclaim', '32979_exclaim', '32983_exclaim', '32984_exclaim', '32986_exclaim', '32987_exclaim', '32988_exclaim', '32991_exclaim', '32992_exclaim', '32997_exclaim', '32_ambigsnopes', '33001_exclaim', '33006_exclaim', '33008_exclaim', '33010_exclaim', '33016_exclaim', '33017_exclaim', '33019_exclaim', '33020_exclaim', '33026_exclaim', '33032_exclaim', '33033_exclaim', '33039_exclaim', '33043_exclaim', '33046_exclaim', '33060_exclaim', '33061_exclaim', '33067_exclaim', '33069_exclaim', '33079_exclaim', '33082_exclaim', '33084_exclaim', '33085_exclaim', '33086_exclaim', '33091_exclaim', '33093_exclaim', '33095_exclaim', '33096_exclaim', '33101_exclaim', '33103_exclaim', '33108_exclaim', '33112_exclaim', '33116_exclaim', '33120_exclaim', '33121_exclaim', '33125_exclaim', '33128_exclaim', '33135_exclaim', '33136_exclaim', '33138_exclaim', '33139_exclaim', '33142_exclaim', '33148_exclaim', '33149_exclaim', '33151_exclaim', '33152_exclaim', '33155_exclaim', '33169_exclaim', '33171_exclaim', '33172_exclaim', '33179_exclaim', '33188_exclaim', '33190_exclaim', '33191_exclaim', '33195_exclaim', '33199_exclaim', '33200_exclaim', '33202_exclaim', '33204_exclaim', '33207_exclaim', '33211_exclaim', '33215_exclaim', '33217_exclaim', '33219_exclaim', '33220_exclaim', '33221_exclaim', '33224_exclaim', '33230_exclaim', '33234_exclaim', '33240_exclaim', '33241_exclaim', '33242_exclaim', '33251_exclaim', '33260_exclaim', '33261_exclaim', '33262_exclaim', '33275_exclaim', '33276_exclaim', '33284_exclaim', '33285_exclaim', '33291_exclaim', '33294_exclaim', '33296_exclaim', '33301_exclaim', '33302_exclaim', '33304_exclaim', '33307_exclaim', '33309_exclaim', '33311_exclaim', '33313_exclaim', '33315_exclaim', '33317_exclaim', '33319_exclaim', '33322_exclaim', '33328_exclaim', '33331_exclaim', '33336_exclaim', '33337_exclaim', '33340_exclaim', '33354_exclaim', '33358_exclaim', '33359_exclaim', '33368_exclaim', '33371_exclaim', '33375_exclaim', '33377_exclaim', '33379_exclaim', '33382_exclaim', '33385_exclaim', '33387_exclaim', '33389_exclaim', '33390_exclaim', '33395_exclaim', '33396_exclaim', '33399_exclaim', '33401_exclaim', '33407_exclaim', '33410_exclaim', '33412_exclaim', '33413_exclaim', '33414_exclaim', '33424_exclaim', '33428_exclaim', '33435_exclaim', '33439_exclaim', '33447_exclaim', '33448_exclaim', '33450_exclaim', '33451_exclaim', '33452_exclaim', '33465_exclaim', '33468_exclaim', '33469_exclaim', '33473_exclaim', '33477_exclaim', '33479_exclaim', '33486_exclaim', '33488_exclaim', '33493_exclaim', '33498_exclaim', '33500_exclaim', '33508_exclaim', '33509_exclaim', '33512_exclaim', '33514_exclaim', '33516_exclaim', '33517_exclaim', '33522_exclaim', '33527_exclaim', '33528_exclaim', '33533_exclaim', '33534_exclaim', '33535_exclaim', '33538_exclaim', '33539_exclaim', '33541_exclaim', '33545_exclaim', '33549_exclaim', '33552_exclaim', '33557_exclaim', '33559_exclaim', '33571_exclaim', '33573_exclaim', '33584_exclaim', '33590_exclaim', '33591_exclaim', '33593_exclaim', '33594_exclaim', '33596_exclaim', '33599_exclaim', '33601_exclaim', '33603_exclaim', '33606_exclaim', '33611_exclaim', '33612_exclaim', '33613_exclaim', '33616_exclaim', '33619_exclaim', '33626_exclaim', '33631_exclaim', '33633_exclaim', '33638_exclaim', '33639_exclaim', '33640_exclaim', '33645_exclaim', '33649_exclaim', '33652_exclaim', '33654_exclaim', '33655_exclaim', '33662_exclaim', '33665_exclaim', '33666_exclaim', '33668_exclaim', '33669_exclaim', '33671_exclaim', '33675_exclaim', '33678_exclaim', '33681_exclaim', '33684_exclaim', '33686_exclaim', '33687_exclaim', '33690_exclaim', '33694_exclaim', '33696_exclaim', '33700_exclaim', '33701_exclaim', '33704_exclaim', '33706_exclaim', '33713_exclaim', '33716_exclaim', '33718_exclaim', '33720_exclaim', '33_ambigsnopes', '34_ambigsnopes', '36_ambigsnopes', '37_ambigsnopes', '38_ambigsnopes', '39_ambigsnopes', '3_ambigsnopes', '40_ambigsnopes', '41_ambigsnopes', '42_ambigsnopes', '43_ambigsnopes', '44_ambigsnopes', '46_ambigsnopes', '47_ambigsnopes', '48_ambigsnopes', '49_ambigsnopes', '4_ambigsnopes', '50_ambigsnopes', '51_ambigsnopes', '52_ambigsnopes', '53_ambigsnopes', '54_ambigsnopes', '55_ambigsnopes', '56_ambigsnopes', '57_ambigsnopes', '58_ambigsnopes', '59_ambigsnopes', '5_ambigsnopes', '60_ambigsnopes', '61_ambigsnopes', '63_ambigsnopes', '64_ambigsnopes', '65_ambigsnopes', '66_ambigsnopes', '67_ambigsnopes', '68_ambigsnopes', '69_ambigsnopes', '6_ambigsnopes', '71_ambigsnopes', '73_ambigsnopes', '74_ambigsnopes', '77_ambigsnopes', '78_ambigsnopes', '79_ambigsnopes', '7_ambigsnopes', '81_ambigsnopes', '83_ambigsnopes', '84_ambigsnopes', '85_ambigsnopes', '87_ambigsnopes', '88_ambigsnopes', '8_ambigsnopes', '90_ambigsnopes', '91_ambigsnopes', '92_ambigsnopes', '93_ambigsnopes', '95_ambigsnopes', '96_ambigsnopes', '98_ambigsnopes', '99_ambigsnopes', '9_ambigsnopes']

,id,file_name,url,source_text_original_chars,source_text_packed_chars,load_error
0,30354_exclaim,30354_1.json,https://www.youtube.com/watch?v=hfJ82VpSulk,388,388,NaN
1,30354_exclaim,30354_2.json,https://www.cnn.com/TRANSCRIPTS/1606/21/sitroo...,46067,46067,NaN
2,30354_exclaim,30354_3.json,https://www.politifact.com/truth-o-meter/state...,15203,15203,NaN
3,30354_exclaim,30354_4.json,https://www.politifact.com/truth-o-meter/state...,17635,17635,NaN
4,30354_exclaim,30354_5.json,https://money.cnn.com/2015/08/31/news/companie...,7900,7900,NaN
5,30354_exclaim,30354_6.json,https://abcnews.go.com/Politics/donald-trump-f...,8818,8818,NaN
6,30354_exclaim,30354_7.json,https://www.forbes.com/sites/debtwire/2015/08/...,10846,10846,NaN
7,30354_exclaim,30354_8.json,https://www.wsj.com/articles/hillary-clinton-t...,14776,14776,NaN
8,30354_exclaim,30354_9.json,https://www.theatlantic.com/politics/archive/2...,33936,33936,NaN
9,30354_exclaim,30354_10.json,https://www.nbcnews.com/news/us-news/trump-ban...,5069,5069,NaN
10,30354_exclaim,30354_11.json,https://www.nbcnews.com/id/6556470/#.V31W1vkrLct,5891,5891,NaN
11,30354_exclaim,30354_12.json,http://www.realclearpolitics.com/video/2016/07...,2332,2332,NaN
12,30354_exclaim,30354_13.json,http://www.nationalreview.com/article/431420/d...,15411,15411,NaN
13,30354_exclaim,30354_14.json,http://articles.philly.com/2004-08-11/news/253...,5542,5542,NaN
14,30354_exclaim,30354_15.json,http://www.upi.com/Archives/1992/03/09/Trumps-...,7376,7376,NaN
15,30354_exclaim,30354_16.json,http://www.upi.com/Archives/1991/06/17/Trump-p...,9207,9207,NaN
16,30354_exclaim,30354_17.json,https://www.usatoday.com/story/news/2016/07/05...,13405,13405,NaN
17,30354_exclaim,30354_18.json,https://www.cnn.com/2016/07/06/politics/donald...,14403,14403,NaN
18,30354_exclaim,30354_19.json,https://www.forbes.com/sites/clareoconnor/2011...,13602,13602,NaN
19,30354_exclaim,30354_20.json,http://www.latimes.com/nation/politics/la-na-t...,20950,20950,NaN


## 5. Stage 1 prompt and JSON validation

Stage 1 chooses only:

- `PROCESS`: readable content exists.
- `SKIP`: no usable readable content exists.

It must **not** judge whether the source proves, supports, or refutes the claim.

In [10]:
ALLOWED_STAGE1_DECISIONS = {"PROCESS", "SKIP"}


def source_key(source: dict) -> str:
    return f'{source["id"]}||{source["file_name"]}||{source["url"]}'


def utc_now() -> str:
    return datetime.now(timezone.utc).isoformat()


def build_stage1_prompt(source: dict) -> str:
    return f"""You are checking whether a scraped source contains usable readable text.

You are NOT judging whether the source is relevant to the claim.
You are NOT checking whether the claim is true.
You are only deciding whether the source has meaningful readable content that a later stage can inspect.

Allowed decisions:
PROCESS = readable content exists.
SKIP = no usable readable content exists.

Choose PROCESS if the source contains any meaningful article text, post text, archive text, screenshot description, claim text, or useful page content.

Choose SKIP only if the source is empty, near-empty, login-only, access-denied, JavaScript-error-only, or menu/footer/cookie-shell-only.

Important:
- If there is readable article-like, post-like, archive-like, or claim-like content anywhere, choose PROCESS.
- Do not decide whether the source proves, supports, or refutes the claim.
- Do not copy source text into your answer.
- Do not return JSON.
- Return exactly three short lines in this format:

DECISION: PROCESS
CONFIDENCE: 0.95
REASON: readable article/post/archive/page content exists

Input:
Claim ID: {source["id"]}
Claim: {source["claim"]}
URL: {source["url"]}
File name: {source["file_name"]}

Source text:
<<<SOURCE_TEXT_START
{source["source_text"]}
SOURCE_TEXT_END>>>
"""


def get_response_text(response) -> str:
    """
    Robustly extract text from a google-genai response.
    response.text is usually enough, but this also checks candidate parts.
    """
    text = getattr(response, "text", None)
    if text:
        return text.strip()

    chunks = []
    try:
        for cand in response.candidates or []:
            content = getattr(cand, "content", None)
            parts = getattr(content, "parts", None) if content else None
            if not parts:
                continue
            for part in parts:
                part_text = getattr(part, "text", None)
                if part_text:
                    chunks.append(part_text)
    except Exception:
        pass

    return "\n".join(chunks).strip()


def summarize_empty_response(response) -> str:
    """
    Helpful debug string when Gemini returns no text.
    """
    bits = []

    try:
        for i, cand in enumerate(response.candidates or []):
            finish_reason = getattr(cand, "finish_reason", None)
            safety_ratings = getattr(cand, "safety_ratings", None)
            bits.append(f"candidate_{i}_finish_reason={finish_reason}")
            if safety_ratings:
                bits.append(f"candidate_{i}_safety_ratings={safety_ratings}")
    except Exception as e:
        bits.append(f"could_not_read_candidates={repr(e)}")

    try:
        usage = getattr(response, "usage_metadata", None)
        if usage:
            bits.append(f"usage_metadata={usage}")
    except Exception:
        pass

    return " | ".join(bits) if bits else "No response diagnostics available."


def parse_stage1_text(raw: str) -> dict:
    """
    Parse plain-text Stage 1 response.
    Expected:
    DECISION: PROCESS
    CONFIDENCE: 0.95
    REASON: ...
    """
    text = (raw or "").strip()

    decision_match = re.search(r"\b(PROCESS|SKIP)\b", text, flags=re.IGNORECASE)
    if not decision_match:
        raise ValueError(f"Could not find PROCESS/SKIP in model output: {text[:500]!r}")

    decision = decision_match.group(1).upper()

    conf_match = re.search(
        r"CONFIDENCE\s*:\s*([01](?:\.\d+)?)",
        text,
        flags=re.IGNORECASE,
    )
    confidence = float(conf_match.group(1)) if conf_match else 0.5
    confidence = max(0.0, min(1.0, confidence))

    reason_match = re.search(
        r"REASON\s*:\s*(.+)",
        text,
        flags=re.IGNORECASE | re.DOTALL,
    )
    reason = reason_match.group(1).strip() if reason_match else "Stage 1 decision parsed from plain-text model output."

    # Keep reason short and single-line.
    reason = re.sub(r"\s+", " ", reason).strip()
    reason = reason[:500]

    return {
        "stage1_decision": decision,
        "stage1_confidence": confidence,
        "stage1_reason": reason,
    }


def validate_stage1_output(obj: dict, source: dict) -> list:
    errors = []

    if not isinstance(obj, dict):
        return ["Output is not a dictionary"]

    decision = obj.get("stage1_decision")
    if decision not in ALLOWED_STAGE1_DECISIONS:
        errors.append(f"stage1_decision must be PROCESS or SKIP, got {decision!r}")

    conf = obj.get("stage1_confidence")
    if not isinstance(conf, (int, float)):
        errors.append("stage1_confidence must be numeric")
    elif not (0.0 <= float(conf) <= 1.0):
        errors.append("stage1_confidence must be between 0.0 and 1.0")

    reason = obj.get("stage1_reason")
    if not isinstance(reason, str) or not reason.strip():
        errors.append("stage1_reason must be a non-empty string")

    return errors


def normalize_stage1_output(obj: dict, source: dict) -> dict:
    """
    Python adds all identity fields.
    The model never copies URLs/file names/IDs.
    """
    return {
        "id": str(source["id"]),
        "claim": source.get("claim", ""),
        "url": source["url"],
        "file_name": source["file_name"],
        "stage1_decision": obj["stage1_decision"],
        "stage1_confidence": float(obj["stage1_confidence"]),
        "stage1_reason": obj["stage1_reason"].strip(),
        "source_text_original_chars": source.get("source_text_original_chars", 0),
        "source_text_packed_chars": source.get("source_text_packed_chars", 0),
        "source_text_was_packed": source.get("source_text_was_packed", False),
        "load_error": source.get("load_error"),
        "stage": "stage1_api_triage",
        "model": STAGE1_MODEL,
        "run_timestamp_utc": utc_now(),
    }


## 6. Stage 1 API call with retries

The fallback is intentionally **fail-open**: if the API repeatedly fails but a source record exists, it returns `PROCESS` with low confidence so later Stage 2 can make the relevance decision. This avoids silently losing potentially useful evidence.

In [11]:
def call_stage1_api(source: dict) -> dict:
    prompt = build_stage1_prompt(source)
    last_error = None
    raw_text = None

    for attempt in range(1, MAX_RETRIES + 1):
        try:
            response = client.models.generate_content(
                model=STAGE1_MODEL,
                contents=prompt,
                config=types.GenerateContentConfig(
                    temperature=STAGE1_TEMPERATURE,
                    max_output_tokens=512,
                    thinking_config=types.ThinkingConfig(thinking_budget=0),
                ),
            )

            raw_text = get_response_text(response)

            if not raw_text:
                diagnostics = summarize_empty_response(response)
                raise ValueError(f"Gemini returned empty text. Diagnostics: {diagnostics}")

            parsed = parse_stage1_text(raw_text)
            errors = validate_stage1_output(parsed, source)

            if errors:
                raise ValueError("; ".join(errors))

            return normalize_stage1_output(parsed, source)

        except Exception as e:
            last_error = repr(e)
            if "429" in last_error or "RESOURCE_EXHAUSTED" in last_error:
                sleep_s = min(20 * attempt, 90) + random.random() * 5
            else:
                sleep_s = min(2 ** attempt, 20) + random.random()

            print(
                f"Stage 1 attempt {attempt}/{MAX_RETRIES} failed for "
                f"{source['id']} {source['file_name']}: {last_error}. Sleeping {sleep_s:.1f}s"
            )
            time.sleep(sleep_s)

    # Stage 1 fail-open fallback:
    # Safer to PROCESS than to accidentally lose evidence.
    return {
        "id": str(source["id"]),
        "claim": source.get("claim", ""),
        "url": source["url"],
        "file_name": source["file_name"],
        "stage1_decision": "PROCESS",
        "stage1_confidence": 0.0,
        "stage1_reason": f"Fail-open fallback after Stage 1 API/validation failure: {last_error}",
        "source_text_original_chars": source.get("source_text_original_chars", 0),
        "source_text_packed_chars": source.get("source_text_packed_chars", 0),
        "source_text_was_packed": source.get("source_text_was_packed", False),
        "load_error": source.get("load_error"),
        "stage": "stage1_api_triage",
        "model": STAGE1_MODEL,
        "run_timestamp_utc": utc_now(),
        "raw_response_preview": (raw_text or "")[:1000],
    }

In [12]:
STAGE1_BATCH_RESPONSE_SCHEMA = {
    "type": "object",
    "properties": {
        "results": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "item_index": {"type": "integer"},
                    "decision": {"type": "string", "enum": ["PROCESS", "SKIP"]},
                    "confidence": {"type": "number"},
                    "reason": {"type": "string"},
                },
                "required": ["item_index", "decision", "confidence", "reason"],
            },
        }
    },
    "required": ["results"],
}


def build_stage1_batch_prompt(batch):
    packed_items = []

    for i, source in enumerate(batch):
        packed_items.append({
            "item_index": i,
            "id": str(source["id"]),
            "claim": source.get("claim", ""),
            "url": source["url"],
            "file_name": source["file_name"],
            "source_text": source.get("source_text", ""),
        })

    expected_indexes = list(range(len(batch)))

    return f"""You are checking whether scraped sources contain usable readable text.

You are NOT judging whether each source is relevant to the claim.
You are NOT checking whether any claim is true.
You are only deciding whether each source has meaningful readable content that a later stage can inspect.

Allowed decisions:
PROCESS = readable content exists.
SKIP = no usable readable content exists.

Choose PROCESS if the source contains any meaningful article text, post text, archive text, screenshot description, claim text, or useful page content.

Choose SKIP only if the source is empty, near-empty, login-only, access-denied, JavaScript-error-only, or menu/footer/cookie-shell-only.

Critical output rules:
- Return exactly {len(batch)} results.
- Required item_index values are exactly: {expected_indexes}
- Do not omit any item_index.
- Do not duplicate any item_index.
- Do not copy source text into the reason.
- Keep reasons short.
- Do not decide whether the source proves, supports, or refutes the claim.

Return strict JSON only:
{{
  "results": [
    {{
      "item_index": 0,
      "decision": "PROCESS",
      "confidence": 0.95,
      "reason": "readable article/post/archive/page content exists"
    }}
  ]
}}

Input batch:
{json.dumps(packed_items, ensure_ascii=False)}
"""


def make_stage1_batch_config():
    return types.GenerateContentConfig(
        temperature=STAGE1_TEMPERATURE,
        response_mime_type="application/json",
        response_schema=STAGE1_BATCH_RESPONSE_SCHEMA,
        max_output_tokens=4096,
        thinking_config=types.ThinkingConfig(thinking_budget=0),
    )


def normalize_stage1_batch_item(model_item, source):
    decision = str(model_item.get("decision", "")).upper().strip()
    if decision not in ALLOWED_STAGE1_DECISIONS:
        decision = "PROCESS"

    try:
        confidence = float(model_item.get("confidence", 0.5))
    except Exception:
        confidence = 0.5

    confidence = max(0.0, min(1.0, confidence))
    reason = re.sub(r"\s+", " ", str(model_item.get("reason", "") or "")).strip()
    if not reason:
        reason = "Stage 1 batch API triage decision."

    return {
        "id": str(source["id"]),
        "claim": source.get("claim", ""),
        "url": source["url"],
        "file_name": source["file_name"],
        "stage1_decision": decision,
        "stage1_confidence": confidence,
        "stage1_reason": reason[:500],
        "source_text_original_chars": source.get("source_text_original_chars", 0),
        "source_text_packed_chars": source.get("source_text_packed_chars", 0),
        "source_text_was_packed": source.get("source_text_was_packed", False),
        "load_error": source.get("load_error"),
        "stage": "stage1_api_triage_batched",
        "model": STAGE1_MODEL,
        "run_timestamp_utc": utc_now(),
    }


def extract_stage1_batch_json(response):
    parsed = getattr(response, "parsed", None)
    if parsed:
        if isinstance(parsed, dict):
            return parsed
        try:
            return json.loads(json.dumps(parsed))
        except Exception:
            pass

    raw = get_response_text(response)
    if not raw:
        diagnostics = summarize_empty_response(response)
        raise ValueError(f"Empty batch response. Diagnostics: {diagnostics}")

    raw = re.sub(r"^```(?:json)?\s*", "", raw.strip(), flags=re.IGNORECASE)
    raw = re.sub(r"\s*```$", "", raw).strip()

    try:
        return json.loads(raw)
    except json.JSONDecodeError:
        start = raw.find("{")
        end = raw.rfind("}")
        if start >= 0 and end > start:
            return json.loads(raw[start:end + 1])
        raise


def call_stage1_batch_api(batch):
    prompt = build_stage1_batch_prompt(batch)
    last_error = None

    for attempt in range(1, MAX_RETRIES + 1):
        try:
            response = client.models.generate_content(
                model=STAGE1_MODEL,
                contents=prompt,
                config=make_stage1_batch_config(),
            )

            parsed = extract_stage1_batch_json(response)
            results = parsed.get("results", [])

            if not isinstance(results, list):
                raise ValueError("Batch response results is not a list")

            by_index = {}
            for item in results:
                if not isinstance(item, dict):
                    continue
                try:
                    idx = int(item.get("item_index"))
                except Exception:
                    continue
                if 0 <= idx < len(batch):
                    by_index[idx] = item

            outputs_by_index = {}

            # Keep all valid returned items.
            for i, source in enumerate(batch):
                model_item = by_index.get(i)
                if model_item is None:
                    continue

                out = normalize_stage1_batch_item(model_item, source)
                errors = validate_stage1_output(out, source)

                if not errors:
                    outputs_by_index[i] = out

            missing = [i for i in range(len(batch)) if i not in outputs_by_index]

            # If only a few items are missing, do NOT retry the whole batch.
            # Use the original API triage for only those missing items.
            if missing:
                print(f"Batch returned {len(outputs_by_index)}/{len(batch)} items; filling missing indexes with per-source API: {missing}")
                for i in missing:
                    outputs_by_index[i] = call_stage1_api(batch[i])

            return [outputs_by_index[i] for i in range(len(batch))]

        except Exception as e:
            last_error = repr(e)

            # 429 needs longer backoff than normal validation errors.
            if "429" in last_error or "RESOURCE_EXHAUSTED" in last_error:
                sleep_s = min(20 * attempt, 90) + random.random() * 5
            else:
                sleep_s = min(2 ** attempt, 20) + random.random()

            print(
                f"Stage 1 batch attempt {attempt}/{MAX_RETRIES} failed for "
                f"batch size {len(batch)}: {last_error}. Sleeping {sleep_s:.1f}s"
            )
            time.sleep(sleep_s)

    # API fallback, not deterministic fallback:
    # If the whole batch repeatedly fails, split into per-source API calls.
    print("Batch failed after retries; falling back to per-source API calls for this batch.")
    return [call_stage1_api(source) for source in batch]


def make_batches(items, batch_size):
    for i in range(0, len(items), batch_size):
        yield items[i:i + batch_size]


## 7. Resume helpers

The output is a JSON list keyed by:

```text
claim_id || file_name || source_url
```

Already processed source records are skipped on rerun.

In [13]:

def load_json_list_if_exists(path: Path) -> list:
    if not path.exists():
        return []
    with path.open("r", encoding="utf-8") as f:
        data = json.load(f)
    if not isinstance(data, list):
        raise TypeError(f"Expected JSON list at {path}, got {type(data)}")
    return data


def save_json_atomic(data, path: Path):
    path.parent.mkdir(parents=True, exist_ok=True)
    tmp_path = path.with_suffix(path.suffix + ".tmp")
    with tmp_path.open("w", encoding="utf-8") as f:
        json.dump(data, f, ensure_ascii=False, indent=2)
    shutil.move(str(tmp_path), str(path))


def index_stage1_outputs(outputs: list) -> dict:
    indexed = {}
    for item in outputs:
        if not isinstance(item, dict):
            continue
        if {"id", "file_name", "url"}.issubset(item.keys()):
            indexed[f'{item["id"]}||{item["file_name"]}||{item["url"]}'] = item
    return indexed

existing_outputs = load_json_list_if_exists(STAGE1_OUT)
existing_by_key = index_stage1_outputs(existing_outputs)

pending_sources = [s for s in source_records if source_key(s) not in existing_by_key]

print("Existing Stage 1 outputs:", len(existing_by_key))
print("Pending Stage 1 sources:", len(pending_sources))

Existing Stage 1 outputs: 0
Pending Stage 1 sources: 8979


## 8. Run Stage 1

This cell saves after every completed API result, so it is safe to interrupt and resume.

In [14]:
all_outputs_by_key = dict(existing_by_key)

pending_batches = list(make_batches(pending_sources, STAGE1_BATCH_SIZE))

print("Pending Stage 1 sources:", len(pending_sources))
print("Pending Stage 1 API batches:", len(pending_batches))
print("Batch size:", STAGE1_BATCH_SIZE)
print("MAX_WORKERS:", MAX_WORKERS)

completed_batches = 0

if not pending_sources:
    print("Nothing to do. Stage 1 output already exists for all source records.")
else:
    with ThreadPoolExecutor(max_workers=MAX_WORKERS) as executor:
        future_to_batch = {
            executor.submit(call_stage1_batch_api, batch): batch
            for batch in pending_batches
        }

        for future in tqdm(as_completed(future_to_batch), total=len(future_to_batch), desc="Stage 1 batched API triage"):
            batch = future_to_batch[future]

            try:
                results = future.result()
            except Exception as e:
                print("Unexpected executor-level batch failure; falling back to per-source API for this batch:", repr(e))
                results = [call_stage1_api(source) for source in batch]

            for source, result in zip(batch, results):
                key = source_key(source)
                all_outputs_by_key[key] = result

            completed_batches += 1

            if completed_batches % SAVE_AFTER_EVERY_COMPLETED_BATCHES == 0:
                save_json_atomic(list(all_outputs_by_key.values()), STAGE1_OUT)
                print(
                    f"Saved {len(all_outputs_by_key)}/{len(source_records)} outputs "
                    f"after {completed_batches}/{len(pending_batches)} completed batches"
                )

stage1_outputs = list(all_outputs_by_key.values())
save_json_atomic(stage1_outputs, STAGE1_OUT)

print("Saved Stage 1 outputs:", STAGE1_OUT)
print("Total Stage 1 outputs:", len(stage1_outputs))

Pending Stage 1 sources: 8979
Pending Stage 1 API batches: 2245
Batch size: 4
MAX_WORKERS: 3

Stage 1 batched API triage:   0%|          | 0/2245 [00:00<?, ?it/s]

Saved 40/8979 outputs after 10/2245 completed batches
Saved 80/8979 outputs after 20/2245 completed batches
Saved 120/8979 outputs after 30/2245 completed batches
Saved 160/8979 outputs after 40/2245 completed batches
Stage 1 batch attempt 1/5 failed for batch size 4: ClientError("429 RESOURCE_EXHAUSTED. {'error': {'code': 429, 'message': 'Resource exhausted. Please try again later. Please refer to https://cloud.google.com/vertex-ai/generative-ai/docs/error-code-429 for more details.', 'status': 'RESOURCE_EXHAUSTED'}}"). Sleeping 21.4s
Saved 200/8979 outputs after 50/2245 completed batches
Saved 240/8979 outputs after 60/2245 completed batches
Saved 280/8979 outputs after 70/2245 completed batches
Saved 320/8979 outputs after 80/2245 completed batches
Saved 360/8979 outputs after 90/2245 completed batches
Stage 1 batch attempt 1/5 failed for batch size 4: ClientError("429 RESOURCE_EXHAUSTED. {'error': {'code': 429, 'message': 'Resource exhausted. Please try again later. Please refer to https://cloud.google.com/vertex-ai/generative-ai/docs/error-code-429 for more details.', 'status': 'RESOURCE_EXHAUSTED'}}"). Sleeping 22.5s
Saved 400/8979 outputs after 100/2245 completed batches
Saved 440/8979 outputs after 110/2245 completed batches
Saved 480/8979 outputs after 120/2245 completed batches
Saved 520/8979 outputs after 130/2245 completed batches
Saved 560/8979 outputs after 140/2245 completed batches
Saved 600/8979 outputs after 150/2245 completed batches
Saved 640/8979 outputs after 160/2245 completed batches
Stage 1 batch attempt 1/5 failed for batch size 4: ClientError("429 RESOURCE_EXHAUSTED. {'error': {'code': 429, 'message': 'Resource exhausted. Please try again later. Please refer to https://cloud.google.com/vertex-ai/generative-ai/docs/error-code-429 for more details.', 'status': 'RESOURCE_EXHAUSTED'}}"). Sleeping 23.3s
Saved 680/8979 outputs after 170/2245 completed batches
Stage 1 batch attempt 1/5 failed for batch size 4: ClientError("429 RESOURCE_EXHAUSTED. {'error': {'code': 429, 'message': 'Resource exhausted. Please try again later. Please refer to https://cloud.google.com/vertex-ai/generative-ai/docs/error-code-429 for more details.', 'status': 'RESOURCE_EXHAUSTED'}}"). Sleeping 22.8s
Saved 720/8979 outputs after 180/2245 completed batches
Stage 1 batch attempt 1/5 failed for batch size 4: ClientError("429 RESOURCE_EXHAUSTED. {'error': {'code': 429, 'message': 'Resource exhausted. Please try again later. Please refer to https://cloud.google.com/vertex-ai/generative-ai/docs/error-code-429 for more details.', 'status': 'RESOURCE_EXHAUSTED'}}"). Sleeping 24.0s
Saved 760/8979 outputs after 190/2245 completed batches
Saved 800/8979 outputs after 200/2245 completed batches
Saved 840/8979 outputs after 210/2245 completed batches
Saved 880/8979 outputs after 220/2245 completed batches
Stage 1 batch attempt 1/5 failed for batch size 4: ClientError("429 RESOURCE_EXHAUSTED. {'error': {'code': 429, 'message': 'Resource exhausted. Please try again later. Please refer to https://cloud.google.com/vertex-ai/generative-ai/docs/error-code-429 for more details.', 'status': 'RESOURCE_EXHAUSTED'}}"). Sleeping 21.3s
Saved 920/8979 outputs after 230/2245 completed batches
Saved 960/8979 outputs after 240/2245 completed batches
Saved 1000/8979 outputs after 250/2245 completed batches
Saved 1040/8979 outputs after 260/2245 completed batches
Stage 1 batch attempt 1/5 failed for batch size 4: ClientError("429 RESOURCE_EXHAUSTED. {'error': {'code': 429, 'message': 'Resource exhausted. Please try again later. Please refer to https://cloud.google.com/vertex-ai/generative-ai/docs/error-code-429 for more details.', 'status': 'RESOURCE_EXHAUSTED'}}"). Sleeping 21.0s
Saved 1080/8979 outputs after 270/2245 completed batches
Saved 1120/8979 outputs after 280/2245 completed batches
Saved 1160/8979 outputs after 290/2245 completed batches
Saved 1200/8979 outputs after 300/2245 completed batches
Stage 1 batch attempt 1/5 failed for batch size 4: ClientError("429 RESOURCE_EXHAUSTED. {'error': {'code': 429, 'message': 'Resource exhausted. Please try again later. Please refer to https://cloud.google.com/vertex-ai/generative-ai/docs/error-code-429 for more details.', 'status': 'RESOURCE_EXHAUSTED'}}"). Sleeping 21.8s
Saved 1240/8979 outputs after 310/2245 completed batches
Saved 1280/8979 outputs after 320/2245 completed batches
Saved 1320/8979 outputs after 330/2245 completed batches
Saved 1360/8979 outputs after 340/2245 completed batches
Stage 1 batch attempt 1/5 failed for batch size 4: ClientError("429 RESOURCE_EXHAUSTED. {'error': {'code': 429, 'message': 'Resource exhausted. Please try again later. Please refer to https://cloud.google.com/vertex-ai/generative-ai/docs/error-code-429 for more details.', 'status': 'RESOURCE_EXHAUSTED'}}"). Sleeping 22.2s
Saved 1400/8979 outputs after 350/2245 completed batches
Saved 1440/8979 outputs after 360/2245 completed batches
Saved 1480/8979 outputs after 370/2245 completed batches
Saved 1520/8979 outputs after 380/2245 completed batches
Saved 1560/8979 outputs after 390/2245 completed batches
Saved 1600/8979 outputs after 400/2245 completed batches
Saved 1640/8979 outputs after 410/2245 completed batches
Stage 1 batch attempt 1/5 failed for batch size 4: ClientError("429 RESOURCE_EXHAUSTED. {'error': {'code': 429, 'message': 'Resource exhausted. Please try again later. Please refer to https://cloud.google.com/vertex-ai/generative-ai/docs/error-code-429 for more details.', 'status': 'RESOURCE_EXHAUSTED'}}"). Sleeping 20.2s
Saved 1680/8979 outputs after 420/2245 completed batches
Saved 1720/8979 outputs after 430/2245 completed batches
Saved 1760/8979 outputs after 440/2245 completed batches
Saved 1800/8979 outputs after 450/2245 completed batches
Saved 1840/8979 outputs after 460/2245 completed batches
Saved 1880/8979 outputs after 470/2245 completed batches
Saved 1920/8979 outputs after 480/2245 completed batches
Stage 1 batch attempt 1/5 failed for batch size 4: ClientError("429 RESOURCE_EXHAUSTED. {'error': {'code': 429, 'message': 'Resource exhausted. Please try again later. Please refer to https://cloud.google.com/vertex-ai/generative-ai/docs/error-code-429 for more details.', 'status': 'RESOURCE_EXHAUSTED'}}"). Sleeping 20.6s
Stage 1 batch attempt 1/5 failed for batch size 4: ClientError("429 RESOURCE_EXHAUSTED. {'error': {'code': 429, 'message': 'Resource exhausted. Please try again later. Please refer to https://cloud.google.com/vertex-ai/generative-ai/docs/error-code-429 for more details.', 'status': 'RESOURCE_EXHAUSTED'}}"). Sleeping 20.7s
Saved 1960/8979 outputs after 490/2245 completed batches
Saved 2000/8979 outputs after 500/2245 completed batches
Saved 2040/8979 outputs after 510/2245 completed batches
Saved 2080/8979 outputs after 520/2245 completed batches
Saved 2120/8979 outputs after 530/2245 completed batches
Saved 2160/8979 outputs after 540/2245 completed batches
Saved 2200/8979 outputs after 550/2245 completed batches
Saved 2240/8979 outputs after 560/2245 completed batches
Saved 2280/8979 outputs after 570/2245 completed batches
Stage 1 batch attempt 1/5 failed for batch size 4: ClientError("429 RESOURCE_EXHAUSTED. {'error': {'code': 429, 'message': 'Resource exhausted. Please try again later. Please refer to https://cloud.google.com/vertex-ai/generative-ai/docs/error-code-429 for more details.', 'status': 'RESOURCE_EXHAUSTED'}}"). Sleeping 24.1s
Saved 2320/8979 outputs after 580/2245 completed batches
Saved 2360/8979 outputs after 590/2245 completed batches
Saved 2400/8979 outputs after 600/2245 completed batches
Stage 1 batch attempt 1/5 failed for batch size 4: ClientError("429 RESOURCE_EXHAUSTED. {'error': {'code': 429, 'message': 'Resource exhausted. Please try again later. Please refer to https://cloud.google.com/vertex-ai/generative-ai/docs/error-code-429 for more details.', 'status': 'RESOURCE_EXHAUSTED'}}"). Sleeping 21.4s
Stage 1 batch attempt 1/5 failed for batch size 4: ClientError("429 RESOURCE_EXHAUSTED. {'error': {'code': 429, 'message': 'Resource exhausted. Please try again later. Please refer to https://cloud.google.com/vertex-ai/generative-ai/docs/error-code-429 for more details.', 'status': 'RESOURCE_EXHAUSTED'}}"). Sleeping 22.4s
Saved 2440/8979 outputs after 610/2245 completed batches
Saved 2480/8979 outputs after 620/2245 completed batches
Saved 2520/8979 outputs after 630/2245 completed batches
Saved 2560/8979 outputs after 640/2245 completed batches
Saved 2600/8979 outputs after 650/2245 completed batches
Saved 2640/8979 outputs after 660/2245 completed batches
Saved 2680/8979 outputs after 670/2245 completed batches
Saved 2720/8979 outputs after 680/2245 completed batches
Saved 2760/8979 outputs after 690/2245 completed batches
Stage 1 batch attempt 1/5 failed for batch size 4: ClientError("429 RESOURCE_EXHAUSTED. {'error': {'code': 429, 'message': 'Resource exhausted. Please try again later. Please refer to https://cloud.google.com/vertex-ai/generative-ai/docs/error-code-429 for more details.', 'status': 'RESOURCE_EXHAUSTED'}}"). Sleeping 22.9s
Saved 2800/8979 outputs after 700/2245 completed batches
Saved 2840/8979 outputs after 710/2245 completed batches
Saved 2880/8979 outputs after 720/2245 completed batches
Saved 2920/8979 outputs after 730/2245 completed batches
Saved 2960/8979 outputs after 740/2245 completed batches
Saved 3000/8979 outputs after 750/2245 completed batches
Saved 3040/8979 outputs after 760/2245 completed batches
Saved 3080/8979 outputs after 770/2245 completed batches
Saved 3120/8979 outputs after 780/2245 completed batches
Stage 1 batch attempt 1/5 failed for batch size 4: ClientError("429 RESOURCE_EXHAUSTED. {'error': {'code': 429, 'message': 'Resource exhausted. Please try again later. Please refer to https://cloud.google.com/vertex-ai/generative-ai/docs/error-code-429 for more details.', 'status': 'RESOURCE_EXHAUSTED'}}"). Sleeping 23.6s
Saved 3160/8979 outputs after 790/2245 completed batches
Saved 3200/8979 outputs after 800/2245 completed batches
Stage 1 batch attempt 1/5 failed for batch size 4: ClientError("429 RESOURCE_EXHAUSTED. {'error': {'code': 429, 'message': 'Resource exhausted. Please try again later. Please refer to https://cloud.google.com/vertex-ai/generative-ai/docs/error-code-429 for more details.', 'status': 'RESOURCE_EXHAUSTED'}}"). Sleeping 24.4s
Saved 3240/8979 outputs after 810/2245 completed batches
Saved 3280/8979 outputs after 820/2245 completed batches
Saved 3320/8979 outputs after 830/2245 completed batches
Saved 3360/8979 outputs after 840/2245 completed batches
Saved 3400/8979 outputs after 850/2245 completed batches
Stage 1 batch attempt 1/5 failed for batch size 4: ClientError("429 RESOURCE_EXHAUSTED. {'error': {'code': 429, 'message': 'Resource exhausted. Please try again later. Please refer to https://cloud.google.com/vertex-ai/generative-ai/docs/error-code-429 for more details.', 'status': 'RESOURCE_EXHAUSTED'}}"). Sleeping 24.7s
Stage 1 batch attempt 1/5 failed for batch size 4: ClientError("429 RESOURCE_EXHAUSTED. {'error': {'code': 429, 'message': 'Resource exhausted. Please try again later. Please refer to https://cloud.google.com/vertex-ai/generative-ai/docs/error-code-429 for more details.', 'status': 'RESOURCE_EXHAUSTED'}}"). Sleeping 23.9s
Saved 3440/8979 outputs after 860/2245 completed batches
Saved 3480/8979 outputs after 870/2245 completed batches
Saved 3520/8979 outputs after 880/2245 completed batches
Stage 1 batch attempt 1/5 failed for batch size 4: ClientError("429 RESOURCE_EXHAUSTED. {'error': {'code': 429, 'message': 'Resource exhausted. Please try again later. Please refer to https://cloud.google.com/vertex-ai/generative-ai/docs/error-code-429 for more details.', 'status': 'RESOURCE_EXHAUSTED'}}"). Sleeping 24.2s
Saved 3560/8979 outputs after 890/2245 completed batches
Saved 3600/8979 outputs after 900/2245 completed batches
Saved 3640/8979 outputs after 910/2245 completed batches
Saved 3680/8979 outputs after 920/2245 completed batches
Saved 3720/8979 outputs after 930/2245 completed batches
Saved 3760/8979 outputs after 940/2245 completed batches
Saved 3800/8979 outputs after 950/2245 completed batches
Stage 1 batch attempt 1/5 failed for batch size 4: ClientError("429 RESOURCE_EXHAUSTED. {'error': {'code': 429, 'message': 'Resource exhausted. Please try again later. Please refer to https://cloud.google.com/vertex-ai/generative-ai/docs/error-code-429 for more details.', 'status': 'RESOURCE_EXHAUSTED'}}"). Sleeping 23.1s
Saved 3840/8979 outputs after 960/2245 completed batches
Saved 3880/8979 outputs after 970/2245 completed batches
Saved 3920/8979 outputs after 980/2245 completed batches
Saved 3960/8979 outputs after 990/2245 completed batches
Saved 4000/8979 outputs after 1000/2245 completed batches
Saved 4040/8979 outputs after 1010/2245 completed batches
Saved 4080/8979 outputs after 1020/2245 completed batches
Stage 1 batch attempt 1/5 failed for batch size 4: ClientError("429 RESOURCE_EXHAUSTED. {'error': {'code': 429, 'message': 'Resource exhausted. Please try again later. Please refer to https://cloud.google.com/vertex-ai/generative-ai/docs/error-code-429 for more details.', 'status': 'RESOURCE_EXHAUSTED'}}"). Sleeping 21.8s
Saved 4120/8979 outputs after 1030/2245 completed batches
Saved 4160/8979 outputs after 1040/2245 completed batches
Saved 4200/8979 outputs after 1050/2245 completed batches
Saved 4240/8979 outputs after 1060/2245 completed batches
Saved 4280/8979 outputs after 1070/2245 completed batches
Saved 4320/8979 outputs after 1080/2245 completed batches
Saved 4360/8979 outputs after 1090/2245 completed batches
Saved 4400/8979 outputs after 1100/2245 completed batches
Saved 4440/8979 outputs after 1110/2245 completed batches
Saved 4480/8979 outputs after 1120/2245 completed batches
Saved 4520/8979 outputs after 1130/2245 completed batches
Stage 1 batch attempt 1/5 failed for batch size 4: ClientError("429 RESOURCE_EXHAUSTED. {'error': {'code': 429, 'message': 'Resource exhausted. Please try again later. Please refer to https://cloud.google.com/vertex-ai/generative-ai/docs/error-code-429 for more details.', 'status': 'RESOURCE_EXHAUSTED'}}"). Sleeping 20.9s
Saved 4560/8979 outputs after 1140/2245 completed batches
Saved 4600/8979 outputs after 1150/2245 completed batches
Saved 4640/8979 outputs after 1160/2245 completed batches
Saved 4680/8979 outputs after 1170/2245 completed batches
Stage 1 batch attempt 1/5 failed for batch size 4: ClientError("429 RESOURCE_EXHAUSTED. {'error': {'code': 429, 'message': 'Resource exhausted. Please try again later. Please refer to https://cloud.google.com/vertex-ai/generative-ai/docs/error-code-429 for more details.', 'status': 'RESOURCE_EXHAUSTED'}}"). Sleeping 21.0s
Saved 4720/8979 outputs after 1180/2245 completed batches
Saved 4760/8979 outputs after 1190/2245 completed batches
Saved 4800/8979 outputs after 1200/2245 completed batches
Stage 1 batch attempt 1/5 failed for batch size 4: ClientError("429 RESOURCE_EXHAUSTED. {'error': {'code': 429, 'message': 'Resource exhausted. Please try again later. Please refer to https://cloud.google.com/vertex-ai/generative-ai/docs/error-code-429 for more details.', 'status': 'RESOURCE_EXHAUSTED'}}"). Sleeping 24.2s
Stage 1 batch attempt 1/5 failed for batch size 4: JSONDecodeError('Unterminated string starting at: line 1 column 437 (char 436)'). Sleeping 2.9s
Saved 4840/8979 outputs after 1210/2245 completed batches
Stage 1 batch attempt 2/5 failed for batch size 4: JSONDecodeError('Unterminated string starting at: line 1 column 437 (char 436)'). Sleeping 4.6s
Saved 4880/8979 outputs after 1220/2245 completed batches
Saved 4920/8979 outputs after 1230/2245 completed batches
Stage 1 batch attempt 3/5 failed for batch size 4: JSONDecodeError('Unterminated string starting at: line 1 column 437 (char 436)'). Sleeping 8.8s
Saved 4960/8979 outputs after 1240/2245 completed batches
Saved 5000/8979 outputs after 1250/2245 completed batches
Stage 1 batch attempt 1/5 failed for batch size 4: ClientError("429 RESOURCE_EXHAUSTED. {'error': {'code': 429, 'message': 'Resource exhausted. Please try again later. Please refer to https://cloud.google.com/vertex-ai/generative-ai/docs/error-code-429 for more details.', 'status': 'RESOURCE_EXHAUSTED'}}"). Sleeping 24.8s
Stage 1 batch attempt 4/5 failed for batch size 4: JSONDecodeError('Unterminated string starting at: line 1 column 437 (char 436)'). Sleeping 16.4s
Saved 5040/8979 outputs after 1260/2245 completed batches
Saved 5080/8979 outputs after 1270/2245 completed batches
Stage 1 batch attempt 5/5 failed for batch size 4: JSONDecodeError('Unterminated string starting at: line 1 column 437 (char 436)'). Sleeping 20.4s
Saved 5120/8979 outputs after 1280/2245 completed batches
Saved 5160/8979 outputs after 1290/2245 completed batches
Batch failed after retries; falling back to per-source API calls for this batch.
Saved 5200/8979 outputs after 1300/2245 completed batches
Stage 1 batch attempt 1/5 failed for batch size 4: ClientError("429 RESOURCE_EXHAUSTED. {'error': {'code': 429, 'message': 'Resource exhausted. Please try again later. Please refer to https://cloud.google.com/vertex-ai/generative-ai/docs/error-code-429 for more details.', 'status': 'RESOURCE_EXHAUSTED'}}"). Sleeping 22.1s
Saved 5240/8979 outputs after 1310/2245 completed batches
Stage 1 batch attempt 2/5 failed for batch size 4: ClientError("429 RESOURCE_EXHAUSTED. {'error': {'code': 429, 'message': 'Resource exhausted. Please try again later. Please refer to https://cloud.google.com/vertex-ai/generative-ai/docs/error-code-429 for more details.', 'status': 'RESOURCE_EXHAUSTED'}}"). Sleeping 43.9s
Stage 1 batch attempt 1/5 failed for batch size 4: ClientError("429 RESOURCE_EXHAUSTED. {'error': {'code': 429, 'message': 'Resource exhausted. Please try again later. Please refer to https://cloud.google.com/vertex-ai/generative-ai/docs/error-code-429 for more details.', 'status': 'RESOURCE_EXHAUSTED'}}"). Sleeping 23.5s
Saved 5280/8979 outputs after 1320/2245 completed batches
Saved 5320/8979 outputs after 1330/2245 completed batches
Stage 1 batch attempt 1/5 failed for batch size 4: ClientError("429 RESOURCE_EXHAUSTED. {'error': {'code': 429, 'message': 'Resource exhausted. Please try again later. Please refer to https://cloud.google.com/vertex-ai/generative-ai/docs/error-code-429 for more details.', 'status': 'RESOURCE_EXHAUSTED'}}"). Sleeping 24.7s
Saved 5360/8979 outputs after 1340/2245 completed batches
Saved 5400/8979 outputs after 1350/2245 completed batches
Saved 5440/8979 outputs after 1360/2245 completed batches
Stage 1 batch attempt 1/5 failed for batch size 4: ClientError("429 RESOURCE_EXHAUSTED. {'error': {'code': 429, 'message': 'Resource exhausted. Please try again later. Please refer to https://cloud.google.com/vertex-ai/generative-ai/docs/error-code-429 for more details.', 'status': 'RESOURCE_EXHAUSTED'}}"). Sleeping 20.5s
Stage 1 batch attempt 1/5 failed for batch size 4: ClientError("429 RESOURCE_EXHAUSTED. {'error': {'code': 429, 'message': 'Resource exhausted. Please try again later. Please refer to https://cloud.google.com/vertex-ai/generative-ai/docs/error-code-429 for more details.', 'status': 'RESOURCE_EXHAUSTED'}}"). Sleeping 20.4s
Saved 5480/8979 outputs after 1370/2245 completed batches
Saved 5520/8979 outputs after 1380/2245 completed batches
Saved 5560/8979 outputs after 1390/2245 completed batches
Stage 1 batch attempt 1/5 failed for batch size 4: ClientError("429 RESOURCE_EXHAUSTED. {'error': {'code': 429, 'message': 'Resource exhausted. Please try again later. Please refer to https://cloud.google.com/vertex-ai/generative-ai/docs/error-code-429 for more details.', 'status': 'RESOURCE_EXHAUSTED'}}"). Sleeping 22.9s
Saved 5600/8979 outputs after 1400/2245 completed batches
Saved 5640/8979 outputs after 1410/2245 completed batches


## 9. Inspect Stage 1 decisions

Look for obvious failures:

- Empty/login/error pages should usually be `SKIP`.
- Perma.cc records, screenshots with meaningful text, readable posts, and article pages should usually be `PROCESS`.
- Stage 1 should not say whether a source is relevant to the claim.

In [15]:
df_stage1 = pd.DataFrame(stage1_outputs)

# Keep a useful display order.
cols = [
    "id",
    "file_name",
    "stage1_decision",
    "stage1_confidence",
    "stage1_reason",
    "source_text_original_chars",
    "source_text_packed_chars",
    "url",
]
cols = [c for c in cols if c in df_stage1.columns]

display(df_stage1[cols].sort_values(["id", "file_name"]).reset_index(drop=True))

print("Decision counts:")
print(df_stage1["stage1_decision"].value_counts(dropna=False))

print("\nPer-claim source counts:")
print(pd.crosstab(df_stage1["id"], df_stage1["stage1_decision"]))

,id,file_name,stage1_decision,stage1_confidence,stage1_reason,source_text_original_chars,source_text_packed_chars,url
0,0_ambigsnopes,1023.txt,SKIP,0.95,empty source text,0,0,https://vinguptamd.com
1,0_ambigsnopes,177.txt,SKIP,0.95,empty source text,0,0,https://www.nbcnews.com/politics/donald-trump/...
2,0_ambigsnopes,317.txt,SKIP,0.95,empty source text,0,0,https://www.bloomberg.com/news/articles/2020-0...
3,0_ambigsnopes,401.txt,SKIP,0.95,empty source text,0,0,https://www.cnn.com/2024/06/27/politics/read-b...
4,0_ambigsnopes,405.txt,SKIP,0.95,empty source text,0,0,https://www.reckitt.com/media-landing/press-re...
...,...,...,...,...,...,...,...,...
8974,9_ambigsnopes,66.txt,SKIP,0.95,empty source text,0,0,https://support.apple.com/en-au/HT202743
8975,9_ambigsnopes,77.txt,SKIP,0.95,empty source text,0,0,https://www.gov.uk/government/news/launch-of-l...
8976,9_ambigsnopes,787.txt,SKIP,0.95,empty source text,0,0,https://www.gov.uk/alerts
8977,9_ambigsnopes,834.txt,SKIP,0.95,empty source text,0,0,https://www.bbc.com/news/uk-64999417
8978,9_ambigsnopes,854.txt,SKIP,0.95,empty source text,0,0,https://assets.publishing.service.gov.uk/gover...

Decision counts:
stage1_decision
PROCESS    5741
SKIP       3238
Name: count, dtype: int64

Per-claim source counts:
stage1_decision  PROCESS  SKIP
id
0_ambigsnopes          0    10
100_ambigsnopes        0    10
104_ambigsnopes        0    10
106_ambigsnopes        0     8
107_ambigsnopes        0     8
...                  ...   ...
95_ambigsnopes         8     1
96_ambigsnopes         0     1
98_ambigsnopes         3     0
99_ambigsnopes         0     4
9_ambigsnopes          0     6

[1158 rows x 2 columns]


## 10. Final Stage 1 validation summary

This re-runs the deterministic validator over saved outputs and reports any identity/schema issues.

In [16]:

source_by_key = {source_key(s): s for s in source_records}
validation_rows = []

for out in stage1_outputs:
    key = f'{out.get("id")}||{out.get("file_name")}||{out.get("url")}'
    source = source_by_key.get(key)
    if source is None:
        validation_rows.append({
            "key": key,
            "valid": False,
            "errors": "Output key not found in Stage 0 source records",
        })
        continue
    errors = validate_stage1_output(out, source)
    validation_rows.append({
        "key": key,
        "id": out.get("id"),
        "file_name": out.get("file_name"),
        "valid": not errors,
        "errors": "; ".join(errors),
    })

validation_df = pd.DataFrame(validation_rows)
display(validation_df)

if validation_df["valid"].all():
    print("✅ All saved Stage 1 outputs passed schema and identity validation.")
else:
    print("⚠️ Some Stage 1 outputs failed validation. Inspect the table above.")

,key,id,file_name,valid,errors
0,30354_exclaim||30354_5.json||https://money.cnn...,30354_exclaim,30354_5.json,True,
1,30354_exclaim||30354_6.json||https://abcnews.g...,30354_exclaim,30354_6.json,True,
2,30354_exclaim||30354_7.json||https://www.forbe...,30354_exclaim,30354_7.json,True,
3,30354_exclaim||30354_8.json||https://www.wsj.c...,30354_exclaim,30354_8.json,True,
4,30354_exclaim||30354_9.json||https://www.theat...,30354_exclaim,30354_9.json,True,
...,...,...,...,...,...
8974,218_ambigsnopes||900.txt||https://www.newspape...,218_ambigsnopes,900.txt,True,
8975,218_ambigsnopes||895.txt||https://www.newspape...,218_ambigsnopes,895.txt,True,
8976,218_ambigsnopes||1099.txt||https://www.newspap...,218_ambigsnopes,1099.txt,True,
8977,218_ambigsnopes||649.txt||https://www.npr.org/...,218_ambigsnopes,649.txt,True,
8978,218_ambigsnopes||488.txt||https://www.wusa9.co...,218_ambigsnopes,488.txt,True,

✅ All saved Stage 1 outputs passed schema and identity validation.


## 11. Next stage handoff

Stage 2 should read:

```python
/content/outputs/stage0/flattened_sources_TARGET10.json
/content/outputs/stage1/stage1_api_triage_TARGET10.json
```

Then it should run claim-aware evidence extraction only for source records where:

```python
stage1_decision == "PROCESS"
```

Remember: Stage 2 should **not** receive `original_rating`.

In [17]:
from pathlib import Path
import shutil

# Drive output folder
DRIVE_STAGE1_DIR = Path("/content/drive/MyDrive/CheckThat_Task3_Dataset/outputs/stage1")
DRIVE_STAGE1_DIR.mkdir(parents=True, exist_ok=True)

# Copy Stage 1 output from Colab runtime to Drive
drive_stage1_path = DRIVE_STAGE1_DIR / STAGE1_OUT.name
shutil.copy2(STAGE1_OUT, drive_stage1_path)

print("Saved Stage 1 output to Drive:")
print(drive_stage1_path)

Saved Stage 1 output to Drive:
/content/drive/MyDrive/CheckThat_Task3_Dataset/outputs/stage1/stage1_api_triage_test_dataset.json

In [18]:
from pathlib import Path
import shutil

# Source file in Colab runtime
stage0_runtime_path = STAGE0_OUT

# Destination folder in Drive
drive_stage0_dir = Path("/content/drive/MyDrive/CheckThat_Task3_Dataset/outputs/stage0")
drive_stage0_dir.mkdir(parents=True, exist_ok=True)

# Destination file
drive_stage0_path = drive_stage0_dir / stage0_runtime_path.name

# Copy
shutil.copy2(stage0_runtime_path, drive_stage0_path)

print("Saved Stage 0 flattened sources to Drive:")
print(drive_stage0_path)

Saved Stage 0 flattened sources to Drive:
/content/drive/MyDrive/CheckThat_Task3_Dataset/outputs/stage0/flattened_sources_test_dataset.json